# Application properties
spring.application.name = SmartSync

# MySql Data-source properties
# spring.datasource.url = jdbc:mysql://localhost:3306/smartSync
# spring.datasource.username = root
# spring.datasource.password = 
# spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Jpa properties
# spring.jpa.hibernate.ddl-auto = update
# spring.jpa.show-sql = true
# spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect

---

# H2 data-source properties
spring.datasource.url=jdbc:h2:mem:smartsyncdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=smartsync
spring.datasource.password=smartsync

spring.h2.console.enabled=true  

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

